apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sprint-luchtenberg-eu
  namespace: default
spec:
  secretName: sprint-luchtenberg-eu-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "sprint.luchtenberg.eu"
  dnsNames:
    - "sprint.luchtenberg.eu"
